"""A contract-accurate fake Sabre Agentic API. Stdlib only.

Replays Sabre's OWN documented example responses at the REAL endpoint paths,
so your agent's paths, request bodies, auth header, and response parsing are
identical to production. Data is from sabre_fixtures.json (generated by
extract_specs.py from the official OpenAPI specs).

    python mock_sabre.py             # serve on http://localhost:8080
    python mock_sabre.py --routes    # list the real routes it serves
    python mock_sabre.py --selftest

Point your backend at it:  SABRE_BASE=http://localhost:8080
Swap to real Sabre later:  SABRE_BASE=https://api.cert.platform.sabre.com  (+ real Bearer token)

NOTE: faithful REPLAY, not stateful — cancelBooking won't alter a later getBooking,
because faking that would mean inventing data that isn't Sabre's. To script a
scenario (e.g. a cancelled flight), edit the payloads in sabre_fixtures.json.
"""
import json
import os
import threading
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, HTTPServer
from urllib.parse import urlparse

HERE = os.path.dirname(os.path.abspath(__file__))
FIX = json.load(open(os.path.join(HERE, "sabre_fixtures.json"), encoding="utf-8"))

# Build {real_path: operation} from the specs' real base + operation paths.
ROUTES = {}
for _api, _d in FIX.items():
    _prefix = urlparse(_d["base"]).path           # e.g. /v1/trip/orders
    for _opid, _o in _d["operations"].items():
        ROUTES[_prefix + _o["path"]] = {**_o, "api": _api, "op": _opid}


def sabre_error(type_, category="APPLICATION"):
    # The real Agentic error envelope (verified against live getHotelRates).
    return {"timestamp": datetime.now(timezone.utc).isoformat(),
            "errors": [{"category": category, "type": type_, "description": ""}]}


class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):  # quiet
        pass

    def _send(self, code, obj):
        body = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _json_body(self):
        n = int(self.headers.get("Content-Length", 0))
        try:
            return json.loads(self.rfile.read(n)) if n else {}
        except ValueError:
            return None

    def do_GET(self):
        if self.path == "/":
            return self._send(200, {"routes": sorted(ROUTES)})
        self._send(404, sabre_error("UNKNOWN_RESOURCE"))

    def do_POST(self):
        if self.path == "/v2/auth/token":
            return self._send(200, {"access_token": "MOCK-TOKEN",
                                    "token_type": "bearer", "expires_in": 604800})

        route = ROUTES.get(self.path)
        if not route:
            return self._send(404, sabre_error("UNKNOWN_RESOURCE"))

        body = self._json_body()
        if body is None:
            return self._send(400, sabre_error("MALFORMED_JSON"))

        # Light realism: if the real example needs a confirmationId, require it.
        req_ex = route["request_example"]
        if isinstance(req_ex, dict) and "confirmationId" in req_ex and "confirmationId" not in body:
            return self._send(400, sabre_error("MISSING_REQUIRED_FIELD.CONFIRMATION_ID"))

        resp = route["response_example"]
        if resp is None:
            return self._send(501, sabre_error("NO_EXAMPLE_IN_SPEC"))  # e.g. checkHotelRate
        self._send(200, resp)


def serve(port=8080):
    print(f"mock sabre on http://localhost:{port}  ({len(ROUTES)} routes; GET / to list)")
    HTTPServer(("127.0.0.1", port), Handler).serve_forever()


def _selftest():
    import urllib.request, urllib.error
    srv = HTTPServer(("127.0.0.1", 8099), Handler)
    threading.Thread(target=srv.serve_forever, daemon=True).start()

    def call(path, payload, expect):
        data = json.dumps(payload).encode()
        req = urllib.request.Request(f"http://localhost:8099{path}", data=data, method="POST",
                                     headers={"Content-Type": "application/json"})
        try:
            r = urllib.request.urlopen(req)
            code, obj = r.status, json.loads(r.read())
        except urllib.error.HTTPError as e:
            code, obj = e.code, json.loads(e.read())
        assert code == expect, f"{path}: got {code}, wanted {expect}"
        return obj

    booking = call("/v1/trip/orders/getBooking", {"confirmationId": "BQAUZG"}, 200)
    assert "travelers" in booking and "flights" in booking, "getBooking shape wrong"
    call("/v1/trip/orders/getBooking", {}, 400)                       # missing confirmationId
    hotels = call("/v1/hotels/hotelSearch",
                  FIX["Hotel Search API - Beta API"]["operations"]["hotelSearch"]["request_example"], 200)
    assert hotels, "hotelSearch returned empty"
    call("/v1/nope/nothing", {}, 404)
    srv.shutdown()
    print(f"selftest ok: {len(ROUTES)} real routes, getBooking returns real Sabre shape "
          f"({len(booking)} top-level fields)")


if __name__ == "__main__":
    import sys
    if "--selftest" in sys.argv:
        _selftest()
    elif "--routes" in sys.argv:
        print("\n".join(f"POST {p}" for p in sorted(ROUTES)))
        print("POST /v2/auth/token")
    else:
        serve()
