"""Scripted-conversation tests for the agent brain. Needs ANTHROPIC_API_KEY.

Drives the brain with sample utterances and asserts it picks the right Sabre
tool and speaks the right facts. This is how you test a voice agent WITHOUT
voice: the calls are generated by Claude's tool-use; we assert on the result.

    export ANTHROPIC_API_KEY=...
    python test_agent_brain.py        # skips with a message if no key
"""
import os
import sys
import threading
from http.server import HTTPServer

from agent_brain import load_env, handle_query  # importing also loads .env

load_env()  # read ANTHROPIC_API_KEY etc. from .env — no need to export in the shell

if not os.environ.get("ANTHROPIC_API_KEY"):
    print("skip: set ANTHROPIC_API_KEY (in .env or the shell) to run brain tests")
    sys.exit(0)

PORT = 8092
os.environ["SABRE_BASE"] = f"http://localhost:{PORT}"

import mock_sabre

# (list of user turns, tool that must be called across the conversation,
#  any-of these substrings expected in the final spoken reply)
CASES = [
    (["Look up booking BQAUZG and tell me who's on it and the flight."],
     "get_booking", ["max", "power", "lh", "439", "dfw", "fra"]),
    (["I want to cancel my entire trip on booking BQAUZG — all the flights.",
      "Yes, I'm certain. Cancel all of them."],
     "cancel_booking", []),
    (["Find hotels near times square, lat 40.757 long -73.985, Aug 21 to 23."],
     "search_hotels", []),
]


def main():
    srv = HTTPServer(("127.0.0.1", PORT), mock_sabre.Handler)
    threading.Thread(target=srv.serve_forever, daemon=True).start()

    for turns, tool, subs in CASES:
        history, all_calls, reply = [], [], ""
        for turn in turns:  # thread the conversation across turns
            reply, history, calls = handle_query(turn, history)
            all_calls += calls
            print(f"   you  > {turn}")
            print(f"   agent> [calls={calls}] {reply[:160]}")
        assert tool in all_calls, f"{turns!r}\n  expected tool {tool}, got {all_calls}"
        if subs:
            low = reply.lower()
            assert any(s in low for s in subs), f"{turns!r}\n  reply missing facts: {reply!r}"
        print(f"ok: {tool:14} <- {turns[0][:48]!r}")

    srv.shutdown()
    print("brain tests ok")


if __name__ == "__main__":
    main()
